version: '3'

services:
  postgres:
    image: 'postgres:15'
    ports:
      - "${PG_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app

  library:
    build:
      context: .
      dockerfile: ./library.dockerfile
    environment:
      - PORT=80
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - PG_DB_NAME=${PG_DB_NAME}
    restart: always
    networks:
      - app
    ports:
      - "${PORT}:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
    entrypoint: [ "/bin/sh", "/app/entrypoint.sh" ]

networks:
  app:

